version: "3.9"

services:
  backend:
    build: .
    ports:
    - 5000:5000
    env_file:
      - .docker-compose.backend.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    volumes:
    - "./db_data:/var/lib/postgresql/data"
    env_file:
      - .docker-compose.postgres.env
  redis:
    image: redis
