"""Add field filename to Code

Revision ID: bb727d43e8e4
Revises: 
Create Date: 2020-12-17 14:30:13.779157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb727d43e8e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('password', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('username', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('role', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
